name: 'branch-script-diff-check'
description: 'compare shell Script results across two branches'
author: 'lainNao'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  compared-branch-name:
    required: true
    description: 'The name of the branch to compare to'
  compared-script:
    required: true
    description: 'The script to run to compare the branches'

outputs:
  isResultSame:
    description: 'Whether the result of the script is the same'
  currentBranchResult:
    description: 'The result of the script on the current branch'
  comparedBranchResult:
    description: 'The result of the script on the compared branch'

runs:
  using: 'node16'
  main: 'dist/index.js'
